eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://ec2-18-221-49-95.us-east-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: AWS-SpringBoot-Eureka
